runtime: python311

# Basic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables for production
env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: false
  MAX_CONTENT_LENGTH: 52428800  # 50MB
  UPLOAD_FOLDER: uploads
  LOG_LEVEL: INFO
  SESSION_TIMEOUT: 3600

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: "/api/status"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/status"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# File upload configuration for large files
handlers:
- url: /.*
  script: auto
  secure: always
